package eu.opertusmundi.common.model.message;

public enum EnumNotificationType {

    CATALOGUE_ASSET_UNPUBLISHED,
    CATALOGUE_HARVEST_COMPLETED,
	ORDER_CONFIRMATION,
	DELIVERY_REQUEST,
	DIGITAL_DELIVERY,
	PURCHASE_REMINDER,
	DIGITAL_DELIVERY_BY_SUPPLIER,
	PHYSICAL_DELIVERY_BY_SUPPLIER,
	DIGITAL_DELIVERY_BY_PLATFORM,
	PURCHASE_REJECTED,
	FILES_UPLOAD_COMPLETED,
    ;

}
