package eu.opertusmundi.common.model.message;

public enum EnumNotificationType {

    ASSET_AVAILABLE_TO_PURCHASE,
    ASSET_PUBLISHED,
    ASSET_PUBLISHING_ACCEPTED,
    ASSET_PUBLISHING_CANCELLED,
    ASSET_PUBLISHING_REJECTED,
    CATALOGUE_ASSET_UNPUBLISHED,
    CATALOGUE_HARVEST_COMPLETED,
    CONSUMER_REGISTRATION_CANCELLED,
    COPY_FILE_TO_TOPIO_DRIVE_ERROR,
    COPY_FILE_TO_TOPIO_DRIVE_SUCCESS,
    DELIVERY_REQUEST,
    DIGITAL_DELIVERY,
    DIGITAL_DELIVERY_BY_PLATFORM,
    DIGITAL_DELIVERY_BY_SUPPLIER,
    FILES_UPLOAD_COMPLETED,
    ORDER_CONFIRMATION,
    PHYSICAL_DELIVERY_BY_SUPPLIER,
    PROVIDER_REGISTRATION_CANCELLED,
    PURCHASE_APPROVED,
    PURCHASE_REJECTED,
    PURCHASE_REMINDER,
    USER_SERVICE_PUBLISH_FAILURE,
    USER_SERVICE_PUBLISH_SUCCESS,
    USER_SERVICE_REMOVE,
    ;

}
