package eu.opertusmundi.common.model.message;

public enum EnumNotificationType {

    CATALOGUE_ASSET_UNPUBLISHED,
    CATALOGUE_HARVEST_COMPLETED,
	ORDER_CONFIRMATION,
	DELIVERY_REQUEST,
	DIGITAL_DELIVERY,
	PURCHASE_REMINDER,
	DIGITAL_DELIVERY_BY_SUPPLIER,
	PHYSICAL_DELIVERY_BY_SUPPLIER,
	DIGITAL_DELIVERY_BY_PLATFORM,
	PURCHASE_APPROVED,
	PURCHASE_REJECTED,
	FILES_UPLOAD_COMPLETED,
	ASSET_PUBLISHING_ACCEPTED,
	ASSET_PUBLISHING_REJECTED,
	ASSET_PUBLISHING_CANCELLED,
	ASSET_PUBLISHED,
	COPY_FILE_TO_TOPIO_DRIVE_SUCCESS,
	COPY_FILE_TO_TOPIO_DRIVE_ERROR,
    ;

}
