package eu.opertusmundi.common.model.email;

public enum EnumMailType {

    ACCOUNT_ACTIVATION_TOKEN,
    ACCOUNT_ACTIVATION_SUCCESS,
    ORDER_CONFIRMATION,
    SUPPLIER_EVALUATION,
    SUPPLIER_DELIVERY_REQUEST,
    SUPPLIER_DIGITAL_DELIVERY,
    SUPPLIER_PURCHASE_REMINDER,
    CONSUMER_DIGITAL_DELIVERY_BY_SUPPLIER,
    CONSUMER_DIGITAL_DELIVERY_BY_PLATFORM,
    CONSUMER_PHYSICAL_DELIVERY_BY_SUPPLIER,
    CONSUMER_RECEIPT_ISSUED,
    CONSUMER_PURCHASE_NOTIFICATION,
    CONSUMER_PURCHASE_REJECTION,
    MASTER_TEMPLATE_CONTRACT_UPDATE,
    FILES_UPLOAD_COMPLETED,
    CATALOGUE_HARVEST_COMPLETED,
    ;

}
