package eu.opertusmundi.common.model.payment;

import java.time.ZonedDateTime;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonIgnoreType;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Base PayIn class
 * 
 * Credited user and wallet are derived from the {@link PayInCommand#userKey}
 * property.
 */
@NoArgsConstructor
@Getter
@Setter
@JsonIgnoreType
public abstract class PayInCommand {

    
    public PayInCommand(
        UUID userKey, UUID orderKey, Integer debitedFunds, String referenceNumber, String payIn, ZonedDateTime createdOn,
        EnumTransactionStatus status, ZonedDateTime executedOn, String resultCode, String resultMessage
    ) {
        super();
        this.userKey         = userKey;
        this.orderKey        = orderKey;
        this.debitedFunds    = debitedFunds;
        this.referenceNumber = referenceNumber;
        this.payIn           = payIn;
        this.createdOn       = createdOn;
        this.status          = status;
        this.executedOn      = executedOn;
        this.resultCode      = resultCode;
        this.resultMessage   = resultMessage;
    }

    /**
     * Platform PayIn unique identifier
     */
    private UUID payInKey = UUID.randomUUID();

    /**
     * User who requested the payment
     */
    private UUID userKey;

    /**
     * Optional order key if this is an order payment
     */
    private UUID orderKey;

    /**
     * Updated by the context e.g. for an order, get the total price including
     * VAT
     */
    private Integer debitedFunds;

    /**
     * Reference number generated by the payment service
     */
    private String referenceNumber;

    /**
     * Payment provider PayIn unique identifier
     */
    private String payIn;

    /**
     * Creation date as set by the payment provider
     */
    private ZonedDateTime createdOn;
    
    /**
     * Transaction status set by the provider
     */
    private EnumTransactionStatus status;
    
    /**
     * Execution date as set by the payment provider
     */
    private ZonedDateTime executedOn;
    
    /**
     * Payment provider error code if operation has failed
     */
    private String resultCode;
    
    /**
     * Payment provider message
     */
    private String resultMessage;
    
    
}
